AWSTemplateFormatVersion: "2010-09-09"
Description: A Kickstart Template
Parameters:
  AWSAccountOwnerNameParameter:
    Description: The github repo name
    Type: String
    Default: <your-name>

  PersonalAccessTokenParameter:
    Description: The github personal Access Token
    Type: String
    Default: None
    NoEcho: true

  ArtifactsBucketParameter:
    Description: The Cloudformation Bucket for artifacts
    Type: String
    Default: <your-name>-cicd-artifacts

  RepositoryOwnerParameter:
    Description: The github account
    Type: String
    Default: <your-github-account>

  RepositoryNameParameter:
    Description: The github repo name
    Type: String
    Default: <your-github-repository>

Resources:
  RepositoryOwnerStoredParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The github account name
      Type: String
      Name:
        Fn::Join:
          - ''
          -
            - /
            - Fn::Join: 
                - '/'
                - 
                  - Ref: AWSAccountOwnerNameParameter
                  - global
                  - parameter
                  - github-owner
      Value:
        Ref: RepositoryOwnerParameter
      Tags:
        Environment: Global
        Project: Kickstart-Zero

  RepositoryNameStoredParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The main github repo name
      Type: String
      Name:
        Fn::Join:
          - ''
          -
            - /
            - Fn::Join: 
                - '/'
                - 
                  - Ref: AWSAccountOwnerNameParameter
                  - global
                  - parameter
                  - root-github-repo
      Value:
        Ref: RepositoryNameParameter
      Tags:
        Environment: Global
        Project: Kickstart-Zero

  AWSAccountOwnerNameStoredParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The AWS Account Owner Name
      Type: String
      Name:
        Fn::Join:
          - ''
          -
            - /
            - Fn::Join: 
                - '/'
                - 
                  - Ref: AWSAccountOwnerNameParameter
                  - global
                  - parameter
                  - aws-owner-name
      Value:
        Ref: AWSAccountOwnerNameParameter
      Tags:
        Environment: Global
        Project: Kickstart-Zero

  PersonalAccessTokenSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: The Github Personal Access Token
      Name: 
        Fn::Join:
          - ''
          -
            - /
            - Fn::Join: 
                - '/'
                - 
                  - Ref: AWSAccountOwnerNameParameter
                  - global
                  - parameter
                  - root-github-token
      SecretString:
        Ref: PersonalAccessTokenParameter
      Tags:
        - Key: Environment
          Value: Global
        - Key: Project
          Value: Kickstart-Zero

  ArtifactsBucketStoredParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The Cloudformation Bucket for artifacts
      Type: String
      Name:
        Fn::Join:
          - ''
          -
            - /
            - Fn::Join: 
                - '/'
                - 
                  - Ref: AWSAccountOwnerNameParameter
                  - global
                  - resource
                  - artifact-bucket
      Value:
        Ref: ArtifactsBucketParameter
      Tags:
        Environment: Global
        Project: Kickstart-Zero

  IsDeployedStoredParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: A Dummy Resource for Defaulting SSM parameters
      Type: String
      Name: /cloudformation/kickstart
      Value: 'yes'
      Tags:
        Environment: Global
        Project: Kickstart-Zero

  ZeroCloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      Description: First and Service Only Role for Cloudformation
      RoleName: ZeroCloudFormationRole
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ZeroCloudFormationZeroPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                - ssm:*tParameter*
                Resource: '*'
              - Effect: Allow
                Action:
                - codepipeline:*tePipeline
                Resource: '*'
              - Effect: Allow
                Action:
                - codepipeline:*agResource
                Resource: '*'
              - Effect: Allow
                Action:
                - codepipeline:ListTagsForResource
                - codepipeline:ListPipelines
                Resource: '*'
              - Effect: Allow
                Action:
                - codepipeline:*teWebhook
                Resource: '*'
              - Effect: Allow
                Action:
                - cloudformation:*
                Resource: '*'

  ZeroCodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      Description: First and Service Only Role for Code Pipeline
      RoleName: ZeroCodePipelineRole
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudFormationZeroPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                - cloudformation:*teStack
                - cloudformation:SetStackPolicy
                Resource: '*'
              - Effect: Allow
                Action:
                - iam:PassRole
                Resource:
                  Fn::GetAtt:
                    - ZeroCloudFormationRole
                    - Arn
              - Effect: Allow
                Action:
                - s3:PutObject
                - s3:GetObject
                Resource:
                  Fn::Join:
                    - ''
                    -
                      - 'arn:aws:s3:::'
                      - Ref: ArtifactsBucketParameter
                      - /*
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess

  TutorialArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        Ref: ArtifactsBucketParameter

  ZeroKickstartPipeline:
    DependsOn:
    - TutorialArtifactsBucket
    - IsDeployedStoredParameter
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Tags:
        - Key: Environment
          Value: Global
        - Key: Project
          Value: Kickstart-Zero
      ArtifactStore:
        Location:
          Ref: ArtifactsBucketParameter
        Type: S3
      Name:
        Fn::Join:
          - '-'
          -
            - Ref: AWSAccountOwnerNameParameter
            - kickstart
            - pipeline
            - zero
      RoleArn:
        Fn::GetAtt:
        - ZeroCodePipelineRole
        - Arn
      # RestartExecutionOnUpdate: true
      Stages: 
        - Name: Source
          Actions:
          - Name: Get-Source
            ActionTypeId:
              Category: Source
              Owner: ThirdParty
              Version: '1'
              Provider: GitHub
            Configuration:
              Owner:
                Ref: RepositoryOwnerParameter
              Repo:
                Ref: RepositoryNameParameter
              Branch: develop
              OAuthToken:
                Ref: PersonalAccessTokenParameter
              PollForSourceChanges: true
            OutputArtifacts:
              - Name: kickstart-artifacts-zero
            RunOrder: 1
        - Name: Deploy
          Actions:
          - Name: Deploy-Kickstart-Dev-Pipeline
            RunOrder: 1
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Version: '1'
              Provider: CloudFormation
            Configuration:
              ActionMode: CREATE_UPDATE
              Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
              RoleArn:
                Fn::GetAtt:
                - ZeroCloudFormationRole
                - Arn
              StackName: 
                Fn::Sub:
                  - ${StackName}-dev
                  - StackName:
                      Ref: AWS::StackName
              TemplatePath: 'kickstart-artifacts-zero::infrastructure/kickstart/kickstart-1.yml'
              ParameterOverrides:
                Fn::Sub:
                - |
                  {
                    "AWSAccountOwnerNameParameter" : "${AWSAccountOwnerName}",
                    "ArtifactsBucketParameter" : "${ArtifactsBucket}",
                    "RepositoryOwnerParameter" : "${RepositoryOwner}",
                    "PersonalAccessTokenNameParameter": "${PersonalAccessToken}",
                    "RepositoryNameParameter" : "${RepositoryName}",
                    "EnvironmentNameParameter": "dev"
                  }
                - AWSAccountOwnerName:
                    Ref: AWSAccountOwnerNameStoredParameter
                  ArtifactsBucket:
                    Ref: ArtifactsBucketStoredParameter
                  RepositoryOwner:
                    Ref: RepositoryOwnerStoredParameter
                  RepositoryName:
                    Ref: RepositoryNameStoredParameter
                  PersonalAccessToken:
                    Fn::Join:
                    - ''
                    -
                      - /
                      - Fn::Join: 
                          - '/'
                          - 
                            - Ref: AWSAccountOwnerNameParameter
                            - global
                            - parameter
                            - root-github-token
            InputArtifacts:
              - Name: kickstart-artifacts-zero
          - Name: Deploy-Kickstart-Stg-Pipeline
            RunOrder: 1
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Version: '1'
              Provider: CloudFormation
            Configuration:
              ActionMode: CREATE_UPDATE
              Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
              RoleArn:
                Fn::GetAtt:
                - ZeroCloudFormationRole
                - Arn
              StackName:
                Fn::Sub:
                  - ${StackName}-stg
                  - StackName:
                      Ref: AWS::StackName
              TemplatePath: 'kickstart-artifacts::infrastructure/kickstart/kickstart-1.yml'
              ParameterOverrides:
                Fn::Sub:
                - |
                  {
                    "AWSAccountOwnerNameParameter" : "${AWSAccountOwnerName}",
                    "ArtifactsBucketParameter" : "${ArtifactsBucket}",
                    "RepositoryOwnerParameter" : "${RepositoryOwner}",
                    "PersonalAccessTokenNameParameter": "${PersonalAccessToken}",
                    "RepositoryNameParameter" : "${RepositoryName}",
                    "EnvironmentNameParameter": "stg"
                  }
                - AWSAccountOwnerName:
                    Ref: AWSAccountOwnerNameStoredParameter
                  ArtifactsBucket:
                    Ref: ArtifactsBucketStoredParameter
                  RepositoryOwner:
                    Ref: RepositoryOwnerStoredParameter
                  RepositoryName:
                    Ref: RepositoryNameStoredParameter
                  PersonalAccessToken:
                    Fn::Join:
                    - ''
                    -
                      - /
                      - Fn::Join: 
                          - '/'
                          - 
                            - Ref: AWSAccountOwnerNameParameter
                            - global
                            - parameter
                            - root-github-token
            InputArtifacts:
              - Name: kickstart-artifacts-zero
          - Name: Deploy-Kickstart-Prd-Pipeline
            RunOrder: 1
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Version: '1'
              Provider: CloudFormation
            Configuration:
              ActionMode: CREATE_UPDATE
              Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
              RoleArn:
                Fn::GetAtt:
                - ZeroCloudFormationRole
                - Arn
              StackName:
                Fn::Sub:
                  - ${StackName}-prd
                  - StackName:
                      Ref: AWS::StackName
              TemplatePath: 'kickstart-artifacts-zero::infrastructure/kickstart/kickstart-1.yml'
              ParameterOverrides:
                Fn::Sub:
                - |
                  {
                    "AWSAccountOwnerNameParameter" : "${AWSAccountOwnerName}",
                    "ArtifactsBucketParameter" : "${ArtifactsBucket}",
                    "RepositoryOwnerParameter" : "${RepositoryOwner}",
                    "PersonalAccessTokenNameParameter": "${PersonalAccessToken}",
                    "RepositoryNameParameter" : "${RepositoryName}",
                    "EnvironmentNameParameter": "prd"
                  }
                - AWSAccountOwnerName:
                    Ref: AWSAccountOwnerNameStoredParameter
                  ArtifactsBucket:
                    Ref: ArtifactsBucketStoredParameter
                  RepositoryOwner:
                    Ref: RepositoryOwnerStoredParameter
                  RepositoryName:
                    Ref: RepositoryNameStoredParameter
                  PersonalAccessToken:
                    Fn::Join:
                    - ''
                    -
                      - /
                      - Fn::Join: 
                          - '/'
                          - 
                            - Ref: AWSAccountOwnerNameParameter
                            - global
                            - parameter
                            - root-github-token
            InputArtifacts:
              - Name: kickstart-artifacts-zero