AWSTemplateFormatVersion: "2010-09-09"
Description: A Kickstart Template
Parameters:
  AWSAccountOwnerNameParameter:
    Description: The github repo name
    Type: String
    Default: <your-name>

  PersonalAccessTokenParameter:
    Description: The github personal Access Token
    Type: String
    Default: None
    NoEcho: true

  ArtifactsBucketParameter:
    Description: The Cloudformation Bucket for artifacts
    Type: String
    Default: <your-name>-cicd-artifacts

  RepositoryOwnerParameter:
    Description: The github account
    Type: String
    Default: <your-github-account>

  RepositoryNameParameter:
    Description: The github repo name
    Type: String
    Default: <your-github-repository>

Resources:
  RepositoryOwnerStoredParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The github account name
      Type: String
      Name:
        Fn::Join:
          - ''
          -
            - /
            - Fn::Join: 
                - '/'
                - 
                  - Ref: AWSAccountOwnerNameParameter
                  - global
                  - parameter
                  - github-owner
      Value:
        Ref: RepositoryOwnerParameter
      Tags:
        Environment: Global
        Project: Kickstart-Zero

  RepositoryNameStoredParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The main github repo name
      Type: String
      Name:
        Fn::Join:
          - ''
          -
            - /
            - Fn::Join: 
                - '/'
                - 
                  - Ref: AWSAccountOwnerNameParameter
                  - global
                  - parameter
                  - root-github-repo
      Value:
        Ref: RepositoryNameParameter
      Tags:
        Environment: Global
        Project: Kickstart-Zero

  AWSAccountOwnerNameStoredParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The AWS Account Owner Name
      Type: String
      Name:
        Fn::Join:
          - ''
          -
            - /
            - Fn::Join: 
                - '/'
                - 
                  - Ref: AWSAccountOwnerNameParameter
                  - global
                  - parameter
                  - aws-owner-name
      Value:
        Ref: AWSAccountOwnerNameParameter
      Tags:
        Environment: Global
        Project: Kickstart-Zero

  PersonalAccessTokenSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: The Github Personal Access Token
      Name: 
        Fn::Join:
          - ''
          -
            - /
            - Fn::Join: 
                - '/'
                - 
                  - Ref: AWSAccountOwnerNameParameter
                  - global
                  - parameter
                  - root-github-token
      SecretString:
        Ref: PersonalAccessTokenParameter
      Tags:
        - Key: Environment
          Value: Global
        - Key: Project
          Value: Kickstart-Zero

  ArtifactsBucketStoredParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The Cloudformation Bucket for artifacts
      Type: String
      Name:
        Fn::Join:
          - ''
          -
            - /
            - Fn::Join: 
                - '/'
                - 
                  - Ref: AWSAccountOwnerNameParameter
                  - global
                  - resource
                  - artifact-bucket
      Value:
        Ref: ArtifactsBucketParameter
      Tags:
        Environment: Global
        Project: Kickstart-Zero

  IsDeployedStoredParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: A Dummy Resource for Defaulting SSM parameters
      Type: String
      Name: /cloudformation/kickstart
      Value: 'yes'
      Tags:
        Environment: Global
        Project: Kickstart-Zero

  ZeroCloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      Description: First and Service Only Role for Cloudformation
      RoleName: 
        Fn::Sub:
          - ${AccountOwner}CloudFormationZeroRole
          - AccountOwner:
              Ref: AWSAccountOwnerNameParameter
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: 
            Fn::Sub:
              - ${AccountOwner}CloudFormationZeroPolicy
              - AccountOwner:
                  Ref: AWSAccountOwnerNameParameter
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                - secretsmanager:GetSecretValue
                Resource:
                  Ref: PersonalAccessTokenSecret
              - Effect: Allow
                Action:
                - iam:Get*
                Resource: '*'
              - Effect: Allow
                Action:
                - iam:*teRole
                - iam:Get*
                - iam:Detach*
                Resource: 
                - Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/dev/CodeBuildRole
                - Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/stg/CodeBuildRole
                - Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/prd/CodeBuildRole
                - Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/dev/CloudFormationRole
                - Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/stg/CloudFormationRole
                - Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/prd/CloudFormationRole
                - Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/dev/CodePipelineRole
                - Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/stg/CodePipelineRole
                - Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/prd/CodePipelineRole
              - Effect: Allow
                Action:
                - iam:*Policy*
                Resource: '*'

#              - Effect: Allow
#                Action:
#                - iam:*Policy*
#                Resource: '*'
#                Condition:
#                  ArnLike:
#                    iam:PolicyArn:
#                      - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/dev/CodePipelinePolicy
#                      - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/stg/CodePipelinePolicy
#                      - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/prd/CodePipelinePolicy
#                      - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/dev/CloudFormationPolicy
#                      - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/stg/CloudFormationPolicy
#                      - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/prd/CloudFormationPolicy
#                      - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/dev/boundaries/MainRoleBoundaryPolicy
#                      - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/stg/boundaries/MainRoleBoundaryPolicy
#                      - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/prd/boundaries/MainRoleBoundaryPolicy
              - Effect: Allow
                Action:
                - ssm:*tParameter*
                Resource: '*'
                Condition:
                  StringLike:
                    "ssm:resourceTag/Environment": Global
              - Effect: Allow
                Action:
                - codepipeline:*tePipeline
                - codepipeline:GetPipeline
                - codepipeline:GetPipelineState
                Resource: '*'
                # - Fn::Sub:
                #   - arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${AWSAccountOwnerName}-kickstart-*
                #   - AWSAccountOwnerName:
                #       Ref: AWSAccountOwnerNameParameter
              - Effect: Allow
                Action:
                - codepipeline:*agResource
                Resource: '*'
              - Effect: Allow
                Action:
                - codepipeline:ListTagsForResource
                - codepipeline:ListPipelines
                Resource: '*'
              - Effect: Allow
                Action:
                - codepipeline:*teWebhook
                Resource: '*'
              - Effect: Allow
                Action:
                - cloudformation:*
                - iam:PassRole
                Resource: '*'
              

  ZeroCodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      Description: First and Service Only Role for Code Pipeline
      RoleName:
        Fn::Sub:
          - ${AccountOwner}CodePipelineZeroRole
          - AccountOwner:
              Ref: AWSAccountOwnerNameParameter
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName:
            Fn::Sub:
              - ${AccountOwner}CodePipelineZeroPolicy
              - AccountOwner:
                  Ref: AWSAccountOwnerNameParameter
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                - cloudformation:*teStack
                - cloudformation:SetStackPolicy
                Resource: '*'
              - Effect: Allow
                Action:
                - iam:PassRole
                Resource:
                  Fn::GetAtt:
                    - ZeroCloudFormationRole
                    - Arn
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess

  TutorialArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        Ref: ArtifactsBucketParameter
#      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
#      PublicAccessBlockConfiguration:
#        BlockPublicAcls: true
#        BlockPublicPolicy: true
#        IgnorePublicAcls: true
#        RestrictPublicBuckets: true

  TutorialBucketPolicy:
    DependsOn: TutorialArtifactsBucket
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: ArtifactsBucketParameter
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action:
          - s3:GetObject
          - s3:PutObject
          Resource:
            Fn::Join:
              - ''
              -
                - 'arn:aws:s3:::'
                - Ref: ArtifactsBucketParameter
                - /*
          Principal: "*"

  ZeroKickstartPipeline:
    DependsOn:
    - TutorialArtifactsBucket
    - IsDeployedStoredParameter
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Tags:
        - Key: Environment
          Value: Global
        - Key: Project
          Value: Kickstart-Zero
      ArtifactStore:
        Location:
          Ref: ArtifactsBucketParameter
        Type: S3
      Name:
        Fn::Join:
          - '-'
          -
            - Ref: AWSAccountOwnerNameParameter
            - kickstart
            - pipeline
            - zero
      RoleArn:
        Fn::GetAtt:
        - ZeroCodePipelineRole
        - Arn
      # RestartExecutionOnUpdate: true
      Stages: 
        - Name: Source
          Actions:
          - Name: Get-Source
            ActionTypeId:
              Category: Source
              Owner: ThirdParty
              Version: '1'
              Provider: GitHub
            Configuration:
              Owner:
                Ref: RepositoryOwnerParameter
              Repo:
                Ref: RepositoryNameParameter
              Branch: develop
              OAuthToken:
                Ref: PersonalAccessTokenParameter
              PollForSourceChanges: true
            OutputArtifacts:
              - Name: kickstart-artifacts-zero
            RunOrder: 1
        - Name: Deploy
          Actions:
          - Name: Deploy-Kickstart-Dev-Pipeline
            RunOrder: 1
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Version: '1'
              Provider: CloudFormation
            Configuration:
              ActionMode: REPLACE_ON_FAILURE 
              Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
              RoleArn:
                Fn::GetAtt:
                - ZeroCloudFormationRole
                - Arn
              StackName: 
                Fn::Sub:
                  - ${StackName}-dev
                  - StackName:
                      Ref: AWS::StackName
              TemplatePath: 'kickstart-artifacts-zero::infrastructure/kickstart/kickstart-1.yml'
              ParameterOverrides:
                Fn::Sub:
                - |
                  {
                    "AWSAccountOwnerNameSSMParameter" : "${AWSAccountOwnerName}",
                    "ArtifactsBucketSSMParameter" : "${ArtifactsBucket}",
                    "RepositoryOwnerSSMParameter" : "${RepositoryOwner}",
                    "PersonalAccessTokenNameParameter": "${PersonalAccessToken}",
                    "RepositoryNameSSMParameter" : "${RepositoryName}",
                    "EnvironmentNameParameter": "dev"
                  }
                - AWSAccountOwnerName:
                    Ref: AWSAccountOwnerNameStoredParameter
                  ArtifactsBucket:
                    Ref: ArtifactsBucketStoredParameter
                  RepositoryOwner:
                    Ref: RepositoryOwnerStoredParameter
                  RepositoryName:
                    Ref: RepositoryNameStoredParameter
                  PersonalAccessToken:
                    Fn::Join:
                    - ''
                    -
                      - /
                      - Fn::Join: 
                          - '/'
                          - 
                            - Ref: AWSAccountOwnerNameParameter
                            - global
                            - parameter
                            - root-github-token
            InputArtifacts:
              - Name: kickstart-artifacts-zero
#          - Name: Deploy-Kickstart-Stg-Pipeline
#            RunOrder: 1
#            ActionTypeId:
#              Category: Deploy
#              Owner: AWS
#              Version: '1'
#              Provider: CloudFormation
#            Configuration:
#              ActionMode: REPLACE_ON_FAILURE 
#              Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
#              RoleArn:
#                Fn::GetAtt:
#                - ZeroCloudFormationRole
#                - Arn
#              StackName:
#                Fn::Sub:
#                  - ${StackName}-stg
#                  - StackName:
#                      Ref: AWS::StackName
#              TemplatePath: 'kickstart-artifacts-zero::infrastructure/kickstart/kickstart-1.yml'
#              ParameterOverrides:
#                Fn::Sub:
#                - |
#                  {
#                    "AWSAccountOwnerNameSSMParameter" : "${AWSAccountOwnerName}",
#                    "ArtifactsBucketSSMParameter" : "${ArtifactsBucket}",
#                    "RepositoryOwnerSSMParameter" : "${RepositoryOwner}",
#                    "PersonalAccessTokenNameParameter": "${PersonalAccessToken}",
#                    "RepositoryNameSSMParameter" : "${RepositoryName}",
#                    "EnvironmentNameParameter": "stg"
#                  }
#                - AWSAccountOwnerName:
#                    Ref: AWSAccountOwnerNameStoredParameter
#                  ArtifactsBucket:
#                    Ref: ArtifactsBucketStoredParameter
#                  RepositoryOwner:
#                    Ref: RepositoryOwnerStoredParameter
#                  RepositoryName:
#                    Ref: RepositoryNameStoredParameter
#                  PersonalAccessToken:
#                    Fn::Join:
#                    - ''
#                    -
#                      - /
#                      - Fn::Join: 
#                          - '/'
#                          - 
#                            - Ref: AWSAccountOwnerNameParameter
#                            - global
#                            - parameter
#                            - root-github-token
#            InputArtifacts:
#              - Name: kickstart-artifacts-zero
#          - Name: Deploy-Kickstart-Prd-Pipeline
#            RunOrder: 1
#            ActionTypeId:
#              Category: Deploy
#              Owner: AWS
#              Version: '1'
#              Provider: CloudFormation
#            Configuration:
#              ActionMode: REPLACE_ON_FAILURE 
#              Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
#              RoleArn:
#                Fn::GetAtt:
#                - ZeroCloudFormationRole
#                - Arn
#              StackName:
#                Fn::Sub:
#                  - ${StackName}-prd
#                  - StackName:
#                      Ref: AWS::StackName
#              TemplatePath: 'kickstart-artifacts-zero::infrastructure/kickstart/kickstart-1.yml'
#              ParameterOverrides:
#                Fn::Sub:
#                - |
#                  {
#                    "AWSAccountOwnerNameSSMParameter" : "${AWSAccountOwnerName}",
#                    "ArtifactsBucketSSMParameter" : "${ArtifactsBucket}",
#                    "RepositoryOwnerSSMParameter" : "${RepositoryOwner}",
#                    "PersonalAccessTokenNameParameter": "${PersonalAccessToken}",
#                    "RepositoryNameSSMParameter" : "${RepositoryName}",
#                    "EnvironmentNameParameter": "prd"
#                  }
#                - AWSAccountOwnerName:
#                    Ref: AWSAccountOwnerNameStoredParameter
#                  ArtifactsBucket:
#                    Ref: ArtifactsBucketStoredParameter
#                  RepositoryOwner:
#                    Ref: RepositoryOwnerStoredParameter
#                  RepositoryName:
#                    Ref: RepositoryNameStoredParameter
#                  PersonalAccessToken:
#                    Fn::Join:
#                    - ''
#                    -
#                      - /
#                      - Fn::Join: 
#                          - '/'
#                          - 
#                            - Ref: AWSAccountOwnerNameParameter
#                            - global
#                            - parameter
#                            - root-github-token
#            InputArtifacts:
#              - Name: kickstart-artifacts-zero