AWSTemplateFormatVersion: "2010-09-09"
Description: A Kickstart Template
Parameters:
  AWSAccountOwnerNameParameter:
    Description: The github repo name
    Type: String
    Default: <your-name>

  PersonalAccessTokenParameter:
    Description: The github personal Access Token
    Type: String
    NoEcho: true
    Default: None

  ArtifactsBucketParameter:
    Description: The Cloudformation Bucket for artifacts
    Type: String
    Default: <your-name>-cicd-artifacts

  RepositoryOwnerParameter:
    Description: The github account
    Type: String
    Default: <your-github-account>

  RepositoryNameParameter:
    Description: The github repo name
    Type: String
    Default: <your-github-repository>

#  AWSAccountOwnerNameSSMParameter:
#    Description: The github repo name
#    Type: String
#    Default: /cloudformation/kickstart
#
#  ArtifactsBucketSSMParameter:
#    Description: The Cloudformation Bucket for artifacts
#    Type: 'AWS::SSM::Parameter::Value<String>'
#    Default: /cloudformation/kickstart
#
#  RepositoryOwnerSSMParameter:
#    Description: The github account
#    Type: 'AWS::SSM::Parameter::Value<String>'
#    Default: /cloudformation/kickstart
#
#  RepositoryNameSSMParameter:
#    Description: The github repo name
#    Type: 'AWS::SSM::Parameter::Value<String>'
#    Default: /cloudformation/kickstart

Resources:
  TutorialArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        Ref: ArtifactsBucketParameter

  # This is a Control Policy that will let all your future roles do anything but create new users
  MainRoleBoundaryPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: MainRoleBoundaryPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          # Allow all services and black list actions
          # Alternatively, a conservative approach would be to whitelist specific services and whitelist/blacklist actions
          - Effect: Allow
            Action: "*"
            Resource: "*"

          # Prevent the creation of new roles without the permissions boundary (cannot self-reference, so policy name is hard-coded)
          # Prevent the replacement of the permissions boundary after new roles have been created
          - Effect: Deny
            Action:
              - iam:CreateRole
              - iam:PutRolePermissionsBoundary
            Resource: "*"
            Condition:
              "StringNotEquals":
                "iam:PermissionsBoundary": !Sub arn:aws:iam::${AWS::AccountId}:policy/PermissionsBoundary


          # Prevent the remove of the permissions boundary on any role
          - Effect: Deny
            Action:
              - iam:DeleteRolePermissionsBoundary
            Resource: "*"
            Condition:
              StringEquals:
                "iam:PermissionsBoundary": !Sub arn:aws:iam::${AWS::AccountId}:policy/PermissionsBoundary

          # Deny modification of this policy (cannot self-reference, so policy name is hard-coded)
          - Effect: Deny
            Action:
              - iam:CreatePolicy*
              - iam:DeletePolicy*
            Resource:
              - !Sub arn:aws:iam::${AWS::AccountId}:policy/PermissionsBoundary

  CloudFormationPolicy:
    Type: AWS::IAM::ManagedPolicy
    DependsOn: MainRoleBoundaryPolicy
    Properties:
      ManagedPolicyName: CloudFormationPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
            - iam:CreateRole
            Resource: '*'
            Condition:
              StringLike:
                'iam:PermissionsBoundary': 
                  Ref: MainRoleBoundaryPolicy

  CodePipelinePolicy:
    DependsOn: 
      - TutorialArtifactsBucket
      - CloudFormationRole
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: CodePipelinePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
            - cloudformation:UpdateStack
            - cloudformation:SetStackPolicy
            Resource: '*'
          - Effect: Allow
            Action:
            - iam:PassRole
            Resource:
              Fn::GetAtt:
                - CloudFormationRole
                - Arn
          - Effect: Allow
            Action:
            - s3:PutObject
            - s3:GetObject
            Resource:
              Fn::Join:
                - ''
                -
                  - 'arn:aws:s3:::'
                  - Ref: ArtifactsBucketParameter
                  - /*

  CloudFormationRole:
    DependsOn: CloudFormationPolicy
    Type: AWS::IAM::Role
    Properties:
      RoleName: CloudFormationRole
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - cloudformation.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
      - arn:aws:iam::aws:policy/AdministratorAccess
      - Ref: CloudFormationPolicy

  CodePipelineRole:
    DependsOn: CodePipelinePolicy
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodePipelineRole
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess
      - Ref: CodePipelinePolicy

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodeBuildRole
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess

  #Now your secret will be safe
  PersonalAccessTokenSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: The Github Personal Access Token
      # A good naming strategy will be very good
      Name:
        Fn::Join:
          - ''
          -
            - /
            - Fn::Join: 
                - '/'
                - 
                  - Ref: AWSAccountOwnerNameParameter
                  - global
                  - github
      SecretString: 
        Ref: PersonalAccessTokenParameter
  
  ArtifactsBucketStoredParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The Cloudformation Bucket for artifacts
      Type: String
      Name:
        Fn::Join:
          - ''
          -
            - /
            - Fn::Join: 
                - '/'
                - 
                  - Ref: AWSAccountOwnerNameParameter
                  - global
                  - resource
                  - artifact-bucket
      Value:
        Ref: ArtifactsBucketParameter

  RepositoryOwnerStoredParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The github account
      Type: String
      Name:
        Fn::Join:
          - ''
          -
            - /
            - Fn::Join: 
                - '/'
                - 
                  - Ref: AWSAccountOwnerNameParameter
                  - global
                  - parameter
                  - github-owner
      Value:
        Ref: RepositoryOwnerParameter

  RepositoryNameStoredParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The github repo name
      Type: String
      Name:
        Fn::Join:
          - ''
          -
            - /
            - Fn::Join: 
                - '/'
                - 
                  - Ref: AWSAccountOwnerNameParameter
                  - global
                  - parameter
                  - github-repo
      Value:
          Ref: RepositoryNameParameter

  AWSAccountOwnerNameStoredParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The AWS Account Owner Name
      Type: String
      Name:
        Fn::Join:
          - ''
          -
            - /
            - Fn::Join: 
                - '/'
                - 
                  - Ref: AWSAccountOwnerNameParameter
                  - global
                  - parameter
                  - aws-owner-name
      Value:
          Ref: AWSAccountOwnerNameParameter

  IsDeployedStoredParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The AWS Account Owner Name
      Type: String
      Name: /cloudformation/kickstart
      Value: yes

  KickstartPipeline:
    DependsOn:
    - TutorialArtifactsBucket
    - CodePipelineRole
    - CloudFormationRole
    - PersonalAccessTokenSecret
    - ArtifactsBucketStoredParameter
    - RepositoryOwnerStoredParameter
    - RepositoryNameStoredParameter
    - AWSAccountOwnerNameStoredParameter
    - IsDeployedStoredParameter
    Type: AWS::CodePipeline::Pipeline
    Properties: 
      ArtifactStore: 
        Location:
          Ref: ArtifactsBucketParameter
        Type: S3
      Name:
        Fn::Join:
          - '-'
          -
            - Ref: AWSAccountOwnerNameParameter
            - kickstart
            - pipeline
      RoleArn:
        Fn::GetAtt:
        - CodePipelineRole
        - Arn
      Stages: 
        - Name: Source
          Actions:
          - Name: Get-Source
            ActionTypeId:
              Category: Source
              Owner: ThirdParty
              Version: '1'
              Provider: GitHub
            Configuration:
              Owner:
                Ref: RepositoryOwnerParameter
              Repo:
                Ref: RepositoryNameParameter
              Branch: develop
              OAuthToken:
                  Ref: PersonalAccessTokenParameter
              PollForSourceChanges: true
            OutputArtifacts:
              - Name: kickstart-artifacts
            RunOrder: 1
        - Name: Deploy
          Actions:
          - Name: Deploy-Kickstart
            RunOrder: 1
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Version: '1'
              Provider: CloudFormation
            Configuration:
              ActionMode: CREATE_UPDATE
              Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
              ChangeSetName: kickstart-changeset
              RoleArn:
                Fn::GetAtt:
                - CloudFormationRole
                - Arn
              StackName: 
                Ref: AWS::StackName
              TemplatePath: 'kickstart-artifacts::infrastructure/kickstart.yml'
              #TemplateConfiguration: 'kickstart-artifacts::infrastructure/kickstart-configuration.json'
              ParameterOverrides:
#                Fn::Sub:
#                - |
#                  {
#                    "AWSAccountOwnerNameParameter" : "${AWSAccountOwnerName}",
#                    "PersonalAccessTokenParameter" : "${PersonalAccessToken}",
#                    "ArtifactsBucketParameter" : "${ArtifactsBucket}",
#                    "RepositoryOwnerParameter" : "${RepositoryOwner}",
#                    "RepositoryNameParameter" : "${RepositoryName}",
#                    "AWSAccountOwnerNameSSMParameter" : "${AWSAccountOwnerNameSSM}",
#                    "ArtifactsBucketSSMParameter" : "${ArtifactsBucketSSM}",
#                    "RepositoryOwnerSSMParameter" : "${RepositoryOwnerSSM}",
#                    "RepositoryNameSSMParameter" : "${RepositoryNameSSM}"
#                  }
                Fn::Sub:
                - |
                  {
                    "AWSAccountOwnerNameParameter" : "${AWSAccountOwnerName}",
                    "PersonalAccessTokenParameter" : "${PersonalAccessToken}",
                    "ArtifactsBucketParameter" : "${ArtifactsBucket}",
                    "RepositoryOwnerParameter" : "${RepositoryOwner}",
                    "RepositoryNameParameter" : "${RepositoryName}"
                  }
                - AWSAccountOwnerName:
                    Ref: AWSAccountOwnerNameParameter
                  PersonalAccessToken:
                    Ref: PersonalAccessTokenParameter
                  ArtifactsBucket:
                    Ref: ArtifactsBucketParameter
                  RepositoryOwner:
                    Ref: RepositoryOwnerParameter
                  RepositoryName:
                    Ref: RepositoryNameParameter
                  #AWSAccountOwnerNameSSM:
                  #  Ref: AWSAccountOwnerNameStoredParameter
                  #ArtifactsBucketSSM:
                  #  Ref: ArtifactsBucketStoredParameter
                  #RepositoryOwnerSSM:
                  #  Ref: RepositoryOwnerStoredParameter
                  #RepositoryNameSSM:
                  #  Ref: RepositoryNameStoredParameter
            InputArtifacts:
              - Name: kickstart-artifacts
Outputs:
  AWSAccountOwnerNameStoredParameterPath:
    Description: The generated path for AWS Account Owner Name parameter
    Value:
      Ref: AWSAccountOwnerNameStoredParameter
  RepositoryNameStoredParameterPath:
    Description: The generated path for Repository Name parameter
    Value:
      Ref: RepositoryNameStoredParameter
  RepositoryOwnerStoredParameterPath:
    Description: The generated path for Repository Owner parameter
    Value:
      Ref: RepositoryOwnerStoredParameter
  ArtifactsBucketStoredParameterPath:
    Description: The generated path for Artifacts Bucket parameter
    Value:
      Ref: ArtifactsBucketStoredParameter
